pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Docker') {
            steps {
                sh 'docker build -t flask-time-app .'
            }
        }
        
        stage('Deploy') {
            steps {
                sh '''
                docker stop flask-app || true
                docker rm flask-app || true
                docker run -d -p 5000:5000 --name flask-app flask-time-app
                '''
            }
        }
        
        stage('Test') {
            steps {
                sh 'sleep 5 && curl -f http://localhost:5000'
            }
        }
    }
    
    post {
        always {
            sh 'docker system prune -f'
        }
    }
}
